"""Offline, monochrome presentation for the private activity dashboard."""

from __future__ import annotations

import base64
import hashlib
import html
import json

from dashboard_assets import read_asset
from dashboard_explore import CONTEXT_JS, INSPECTOR_JS
from dashboard_styles import CSS

JS = CONTEXT_JS + INSPECTOR_JS + read_asset("dashboard.js")



def icon(name: str) -> str:
    paths = {
        "clock": "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 7v5l3 2",
        "day": "M4 4h6v6H4z M14 4h6v6h-6z M4 14h6v6H4z M14 14h6v6h-6z",
        "week": "M4 19V9 M9 19V5 M14 19v-8 M19 19V3",
        "month": "M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16 M8 14h1 M13 14h1",
        "year": "M4 4h16v16H4z M4 10h16 M10 4v16 M16 4v16 M4 16h16",
        "person": "M8 7a4 4 0 1 0 8 0 4 4 0 0 0-8 0 M4 21v-3a8 8 0 0 1 16 0v3",
        "data": "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 11v6 M12 7h.01",
        "refresh": "M20 7v5h-5 M4 17v-5h5 M6 7a7 7 0 0 1 12-1l2 3 M18 17a7 7 0 0 1-12 1l-2-3",
        "right": "m9 5 7 7-7 7", "left": "m15 5-7 7 7 7",
        "lock": "M6 10h12v11H6z M8 10V7a4 4 0 0 1 8 0v3 M12 14v3",
        "export": "M12 3v12 M8 7l4-4 4 4 M5 13v7h14v-7",
    }
    return f'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="{paths[name]}"/></svg>'


def overview(prefix: str, title: str) -> str:
    return f'''<section class="primary-visual"><div class="section-heading"><h2>{title}</h2><div class="activity-legend"><span><i></i>Identified Mac</span><span><i class="unknown"></i>Window unknown</span><span><i class="phone"></i>iPhone</span></div></div><div class="chart-scroll" id="{prefix}-activity"></div><div class="activity-detail" id="{prefix}-activity-detail" aria-live="polite"></div><p class="timeline-note">Devices can overlap. Dotted dates have no record.</p></section>{summary(prefix)}'''


def summary(prefix: str) -> str:
    return f'''<div class="summary-grid"><section class="time-breakdown"><h2>Where your time went</h2><div id="{prefix}-topics"></div></section><section class="continuity"><h2>Continuity</h2><div id="{prefix}-focus"></div><p class="evidence-note">Model topics are estimates. Devices can overlap.</p></section></div>'''


def period_details(prefix: str) -> str:
    return f'''<details class="records-detail"><summary>Explore records</summary><div class="detail-content"><section class="panel"><h2>Workstreams over time</h2><div class="chart-scroll" id="{prefix}-evolution"></div><div class="chart-detail" id="{prefix}-evolution-detail" aria-live="polite"></div></section><div class="grid"><section class="panel"><h2>Workstream details</h2><div class="app-list" id="{prefix}-workstreams"></div></section><section class="panel"><h2>Mac apps</h2><div class="app-list" id="{prefix}-mac-apps"></div></section><section class="panel"><h2>iPhone apps</h2><div class="app-list" id="{prefix}-phone-apps"></div></section><section class="panel optional-panel"><h2>Labels you confirmed</h2><div id="{prefix}-user-tasks"></div></section><section class="panel optional-panel"><h2>Visible-screen suggestions</h2><div id="{prefix}-screen-workstreams"></div></section><section class="panel"><h2>Work artifacts</h2><div id="{prefix}-artifacts"></div></section><section class="panel hidden" id="{prefix}-results-panel"><h2>Results you confirmed</h2><div id="{prefix}-results-list"></div></section><section class="panel hidden" id="{prefix}-browser-panel"><h2>Websites in focus</h2><div id="{prefix}-browser-sites"></div></section><section class="panel hidden" id="{prefix}-calendar-panel"><h2>Planned time and completed reminders</h2><div id="{prefix}-calendar-summary"></div></section></div></div></details>'''


def render(data: dict) -> bytes:
    packed = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    packed = packed.replace("<", "\\u003c").replace(">", "\\u003e").replace("&", "\\u0026")
    packed = packed.replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    css_hash = base64.b64encode(hashlib.sha256(CSS.encode()).digest()).decode()
    js_hash = base64.b64encode(hashlib.sha256(JS.encode()).digest()).decode()
    csp = ("default-src 'none'; base-uri 'none'; form-action 'none'; connect-src 'none'; "
           "img-src 'none'; font-src 'none'; object-src 'none'; frame-src 'none'; "
           f"style-src 'sha256-{css_hash}'; script-src 'sha256-{js_hash}'")
    fixture_notice = '<div class="fixture-banner">Design preview · fabricated example data</div>' if data.get("synthetic_fixture") else ""
    document = f"""<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="{html.escape(csp, quote=True)}"><title>Your time</title><style>{CSS}</style></head><body>
<div class="shell"><header class="app-header"><div class="brand">Your time</div><nav class="tabs" role="tablist" aria-label="Chronicle views" aria-orientation="horizontal"><button class="tab" role="tab" data-target="day" aria-controls="day-view" aria-selected="true">Day</button><button class="tab" role="tab" data-target="week" aria-controls="week-view" aria-selected="false">Week</button><button class="tab" role="tab" data-target="month" aria-controls="month-view" aria-selected="false">Month</button><button class="tab" role="tab" data-target="year" aria-controls="year-view" aria-selected="false">Year</button></nav><div class="toolbar"><div class="date-nav"><button class="control-button" id="prev-period" type="button" aria-label="Previous period">{icon("left")}</button><label class="period-control" data-period="day"><select id="day" aria-label="Day"></select></label><label class="period-control hidden" data-period="week"><select id="week" aria-label="Week ending"></select></label><label class="period-control hidden" data-period="month"><select id="month" aria-label="Month"></select></label><label class="period-control hidden" data-period="year"><select id="year" aria-label="Year"></select></label><button class="control-button" id="next-period" type="button" aria-label="Next period">{icon("right")}</button></div><button class="control-button" id="jump-latest" type="button">Latest</button></div></header>
<main>{fixture_notice}<div class="page-head"><div class="date-heading"><p id="view-subtitle"></p><h1 id="view-title"></h1></div><div class="stats" id="stats"></div></div>
<section class="view" data-view="day" id="day-view" role="tabpanel"><p class="data-alert hidden" id="data-alert"></p><section class="primary-visual"><div class="section-heading"><h2>Your day</h2><div class="device-switch"><button id="context-range-active" type="button" aria-pressed="true">Active hours</button><button id="context-range-full" type="button" aria-pressed="false">24 hours</button></div></div><div id="day-timeline"></div><div class="timeline-inspector"><div class="timeline-detail" id="timeline-detail" aria-live="polite"></div><div id="timeline-controls"><button class="control-button" id="timeline-prev" aria-label="Previous interval">{icon("left")}</button><button class="control-button" id="timeline-next" aria-label="Next interval">{icon("right")}</button></div></div><p class="timeline-note">Recorded foreground intervals. Gaps may include idle time or missing observations. Hatched blocks have no window identity.</p></section>{summary("day")}
<details class="records-detail"><summary>Explore records</summary><div class="detail-content"><div class="record-actions"><button class="control-button" id="save-day" type="button">Day review</button></div><section class="panel"><h2>Activity log</h2><div id="activity-log"></div></section><section class="panel"><div class="panel-header"><h2>Context stretches</h2></div><div class="chart-scroll" id="context-map"></div><div class="chart-detail" id="context-detail" aria-live="polite"></div><p class="quiet">Stretches of at least two minutes. Model labels are unverified.</p></section><section class="panel"><h2>Activity by hour</h2><div class="chart-scroll" id="day-activity"></div><div class="activity-detail" id="day-activity-detail"></div></section><div class="grid"><section class="panel"><h2>Workstream details</h2><p id="focus-summary" class="quiet"></p><div id="workmap" class="workmap"></div><div id="workstreams" class="app-list"></div><details class="workstream-secondary"><summary>Other observed context</summary><div class="app-list" id="broad-workstreams"></div></details><div class="confirmed-task"><h3>Confirmed by you</h3><div id="user-task-labels"></div></div><div class="screen-context"><h3>Visible-screen suggestions</h3><div id="screen-workstreams"></div></div></section><section class="panel"><h2>Mac apps</h2><div class="app-list" id="mac-apps"></div></section><section class="panel"><h2>iPhone apps</h2><div class="app-list" id="iphone-apps"></div></section><section class="panel" id="day-rhythm-panel"><h2>Hourly rhythm</h2><div id="rhythm"></div></section><section class="panel"><h2>Work artifacts</h2><div id="work-artifacts"></div><p class="quiet">Commits and changed files indicate activity; they do not confirm delivery.</p></section><section class="panel hidden" id="results-panel"><h2>Results you confirmed</h2><div id="results-list"></div></section><section class="panel hidden" id="browser-panel"><h2>Websites in focus</h2><div id="browser-sites"></div></section><section class="panel hidden" id="calendar-panel"><h2>Planned time and completed reminders</h2><div id="calendar-day"></div></section></div><section class="panel" id="day-score-section"><h2>Five-minute device samples</h2><div class="score-scroll"><svg class="score" id="score" role="group" aria-label="Mac and iPhone samples aligned across the day"></svg></div><div class="score-detail"><strong id="score-time"></strong><p id="score-mac"></p><p id="score-phone"></p></div></section><details id="day-chapters" class="chapter-detail"><summary>Activity chapters</summary><div id="tag-filters" class="filters"></div><div id="chapters"></div></details><p class="quiet" id="day-caveat"></p></div></details></section>
<section class="view hidden" data-view="week" id="week-view" role="tabpanel">{overview("week","Your week")}<details class="records-detail"><summary>Explore records</summary><div class="detail-content"><section class="panel"><h2>Workstreams over time</h2><div class="chart-scroll" id="week-evolution"></div><div class="chart-detail" id="week-evolution-detail"></div></section><section class="panel"><div class="panel-header"><h2>Activity across the week</h2><div class="device-switch"><button id="week-mac-toggle" aria-pressed="true">Mac</button><button id="week-phone-toggle" aria-pressed="false">iPhone</button></div></div><div id="week-heatmap"></div><div class="heatmap-axis"><span>12 am</span><span>6 am</span><span>12 pm</span><span>6 pm</span><span>11 pm</span></div></section><div class="grid"><section class="panel"><h2>Mac foreground</h2><div id="week-mac"></div></section><section class="panel"><h2>iPhone app time</h2><div id="week-phone"></div></section><section class="panel"><h2>Mac apps</h2><div id="week-mac-apps"></div></section><section class="panel"><h2>iPhone apps</h2><div id="week-apps"></div></section><section class="panel"><h2>Work artifacts</h2><div id="week-artifacts"></div></section><section class="panel hidden" id="week-browser-panel"><h2>Websites in focus</h2><div id="week-browser-sites"></div></section></div></div></details></section>
<section class="view hidden" data-view="month" id="month-view" role="tabpanel">{overview("month","Your month")}<details class="records-detail"><summary>Day by day</summary><div class="detail-content"><div class="calendar-head"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span></div><div class="calendar" id="month-calendar"></div><p class="quiet">Empty days have no record. Device totals remain separate.</p></div></details>{period_details("month")}</section>
<section class="view hidden" data-view="year" id="year-view" role="tabpanel">{overview("year","Your year")}<details class="records-detail"><summary>Month by month</summary><div class="detail-content"><div class="month-grid" id="year-months"></div></div></details>{period_details("year")}</section>
<footer><details class="coverage-panel" id="coverage-panel"><summary>Data coverage and limits</summary><p>Mac and iPhone activity can overlap. No input for three minutes is classified as idle, so reading or calls can appear idle. A visible screen supports context, not completion. Time without a sample stays unknown.</p><div class="detail-grid" id="coverage"></div></details><div class="footer-actions"><span id="updated"></span><button id="refresh" class="control-button">Refresh</button><button id="coverage-link" class="control-button">Coverage</button></div></footer></main></div><dialog class="context-dialog" id="context-dialog" aria-labelledby="context-title"><div class="panel-header"><h2 id="context-title"></h2><button class="control-button" id="context-close" type="button">Close</button></div><div class="context-heading"><strong id="context-total"></strong><span id="context-source"></span></div><div id="context-body"></div></dialog><dialog class="review-dialog" id="review-dialog" aria-labelledby="review-title"><div class="panel-header"><h2 id="review-title">Day review</h2><button class="control-button" id="review-close">Close</button></div><textarea id="review-json" readonly aria-label="Day review JSON" spellcheck="false"></textarea><div class="review-actions"><button class="control-button" id="review-copy">Copy JSON</button><p class="quiet" id="review-status" aria-live="polite"></p></div></dialog><script type="application/json" id="snapshot">{packed}</script><script>{JS}</script></body></html>"""
    return document.encode("utf-8")
